//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PinkBus.Services.Infrastructure.SmsWs {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SmsWs.MKSMSWSSoap")]
    public interface MKSMSWSSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CreateNewSMSSender", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool CreateNewSMSSender(string phonenumber, string smsmessage, int typeid, string scheduletime);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CreateNewSMSSender", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> CreateNewSMSSenderAsync(string phonenumber, string smsmessage, int typeid, string scheduletime);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CreateNewSMSSenderBatch", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void CreateNewSMSSenderBatch(System.Data.DataSet smset);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CreateNewSMSSenderBatch", ReplyAction="*")]
        System.Threading.Tasks.Task CreateNewSMSSenderBatchAsync(System.Data.DataSet smset);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface MKSMSWSSoapChannel : PinkBus.Services.Infrastructure.SmsWs.MKSMSWSSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MKSMSWSSoapClient : System.ServiceModel.ClientBase<PinkBus.Services.Infrastructure.SmsWs.MKSMSWSSoap>, PinkBus.Services.Infrastructure.SmsWs.MKSMSWSSoap {
        
        public MKSMSWSSoapClient() {
        }
        
        public MKSMSWSSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MKSMSWSSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MKSMSWSSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MKSMSWSSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool CreateNewSMSSender(string phonenumber, string smsmessage, int typeid, string scheduletime) {
            return base.Channel.CreateNewSMSSender(phonenumber, smsmessage, typeid, scheduletime);
        }
        
        public System.Threading.Tasks.Task<bool> CreateNewSMSSenderAsync(string phonenumber, string smsmessage, int typeid, string scheduletime) {
            return base.Channel.CreateNewSMSSenderAsync(phonenumber, smsmessage, typeid, scheduletime);
        }
        
        public void CreateNewSMSSenderBatch(System.Data.DataSet smset) {
            base.Channel.CreateNewSMSSenderBatch(smset);
        }
        
        public System.Threading.Tasks.Task CreateNewSMSSenderBatchAsync(System.Data.DataSet smset) {
            return base.Channel.CreateNewSMSSenderBatchAsync(smset);
        }
    }
}
